import Head from 'next/head'
import { useEffect, useState } from 'react';
import LoginRegisterAPP from '../app/page/login-register-app'
import LoginRegisterPC from '../app/page/login-register-pc'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [chromeWidth, setChromeWidth] = useState(0);
  let resizeWindow = () => {
    setChromeWidth(window.innerWidth);
  };
  useEffect(() => {
    resizeWindow();
    window.addEventListener("resize", resizeWindow);
    return () => window.removeEventListener("resize", resizeWindow);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>{chromeWidth > 1024 ? <LoginRegisterPC /> : <LoginRegisterAPP />} </>;
    </div>
  )
}
